<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net10.0</TargetFrameworks>
		<LangVersion>Latest</LangVersion>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<OutputType>Exe</OutputType>
		<StartupObject>unforge.cli.Program</StartupObject>
		<Configurations>Debug;Release;SelfContained</Configurations>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<Optimize>False</Optimize>
		<DebugType>full</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<DefineConstants>TRACE;DEBUG</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<Optimize>True</Optimize>
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='SelfContained'">
	  <Optimize>True</Optimize>
	  <DebugType>none</DebugType>
	  <DebugSymbols>false</DebugSymbols>
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
		<PublishTrimmed>true</PublishTrimmed>
		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
		<TrimMode>partial</TrimMode>
	</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\unforge\unforge.csproj" />
  </ItemGroup>

</Project>
